/**
 * API Endpoint Functions - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * Each function wraps the project's API client with the correct path, method,
 * and TypeScript types from api-generated.ts.
 */

import { get, post, put } from '@/lib/api/client';
import { apiClient } from '@/lib/api/client';
import type {
  PaymentRead,
  PaymentReadList,
  PaymentBatchRead,
  PaymentBatchReadList,
  PaymentsDashboardRead,
  PaymentListParams,
  PaymentBatchListParams,
  CreatePaymentBatchRequest,
  ParkPaymentsRequest,
  UnparkPaymentsRequest,
} from '@/types/api-generated';
import type { DefaultResponse } from '@/types/api';

// --- Payments ---

/**
 * Get a list of all payments, optionally filtered
 */
export const getPayments = (params?: PaymentListParams) =>
  get<PaymentReadList>('/v1/payments', params);

/**
 * Get a single payment by ID
 */
export const getPayment = (id: number) =>
  get<PaymentRead>(`/v1/payments/${id}`);

/**
 * Park one or more payments
 */
export const parkPayments = (data: ParkPaymentsRequest) =>
  put<void>('/v1/payments/park', data);

/**
 * Unpark one or more payments
 */
export const unparkPayments = (data: UnparkPaymentsRequest) =>
  put<void>('/v1/payments/unpark', data);

/**
 * Get dashboard data (metrics, charts, agency summary)
 */
export const getDashboard = () =>
  get<PaymentsDashboardRead>('/v1/payments/dashboard');

// --- Payment Batches ---

/**
 * Get a list of all payment batches, optionally filtered
 */
export const getPaymentBatches = (params?: PaymentBatchListParams) =>
  get<PaymentBatchReadList>('/v1/payment-batches', params);

/**
 * Get a single payment batch by ID
 */
export const getPaymentBatch = (id: number) =>
  get<PaymentBatchRead>(`/v1/payment-batches/${id}`);

/**
 * Create a new payment batch from selected payment IDs
 * Requires LastChangedUser header for audit trail
 */
export const createPaymentBatch = (
  data: CreatePaymentBatchRequest,
  lastChangedUser: string,
) => post<DefaultResponse>('/v1/payment-batches', data, lastChangedUser);

/**
 * Download invoice PDF for a payment batch
 * Returns binary blob data
 */
export const downloadInvoicePdf = (id: number) =>
  apiClient<Blob>(`/v1/payment-batches/${id}/download-invoice-pdf`, {
    method: 'POST',
    isBinaryResponse: true,
  });

// --- Demo ---

/**
 * Reset demo data to initial state
 */
export const resetDemo = () => post<void>('/demo/reset-demo');
