/**
 * API Types - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * These types correspond to the `components/schemas` section of the OpenAPI spec.
 * The existing base types (APIError, APIRequestConfig, etc.) remain in api.ts.
 */

import type { DefaultResponse } from '@/types/api';

// Re-export DefaultResponse for convenience
export type { DefaultResponse };

/**
 * PaymentRead - Individual payment record
 */
export interface PaymentRead {
  Id?: number;
  Reference?: string;
  AgencyName?: string;
  ClaimDate?: string;
  AgentName?: string;
  AgentSurname?: string;
  LastChangedUser?: string;
  LastChangedDate?: string;
  BondAmount?: number;
  CommissionType?: string;
  GrantDate?: string;
  RegistrationDate?: string;
  Bank?: string;
  CommissionAmount?: number;
  VAT?: number;
  Status?: string;
  BatchId?: number | null;
}

/**
 * PaymentReadList - Wrapper for list of payments
 */
export interface PaymentReadList {
  PaymentList?: PaymentRead[];
}

/**
 * PaymentBatchRead - Payment batch record
 */
export interface PaymentBatchRead {
  Id?: number;
  CreatedDate?: string;
  Status?: string;
  Reference?: string;
  LastChangedUser?: string;
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionAmount?: number;
  TotalVat?: number;
}

/**
 * PaymentBatchReadList - Wrapper for list of payment batches
 */
export interface PaymentBatchReadList {
  PaymentBatchList?: PaymentBatchRead[];
}

/**
 * PaymentStatusReportItem - Dashboard status report entry
 */
export interface PaymentStatusReportItem {
  Status?: string;
  PaymentCount?: number;
  TotalPaymentAmount?: number;
  CommissionType?: string;
  AgencyName?: string;
}

/**
 * ParkedPaymentsAgingReportItem - Dashboard aging report entry
 */
export interface ParkedPaymentsAgingReportItem {
  Range?: string;
  AgencyName?: string;
  PaymentCount?: number;
}

/**
 * PaymentsByAgencyReportItem - Dashboard agency summary entry
 */
export interface PaymentsByAgencyReportItem {
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionCount?: number;
  Vat?: number;
}

/**
 * PaymentsDashboardRead - Full dashboard response
 */
export interface PaymentsDashboardRead {
  PaymentStatusReport?: PaymentStatusReportItem[];
  ParkedPaymentsAgingReport?: ParkedPaymentsAgingReportItem[];
  TotalPaymentCountInLast14Days?: number;
  PaymentsByAgency?: PaymentsByAgencyReportItem[];
}

/**
 * CreatePaymentBatchRequest - Request body for creating a payment batch
 */
export interface CreatePaymentBatchRequest {
  PaymentIds?: number[];
}

/**
 * ParkPaymentsRequest - Request body for parking payments
 */
export interface ParkPaymentsRequest {
  PaymentIds?: number[];
}

/**
 * UnparkPaymentsRequest - Request body for unparking payments
 */
export interface UnparkPaymentsRequest {
  PaymentIds?: number[];
}

/**
 * Query parameter types for payment list filtering
 */
export type PaymentListParams = {
  ClaimDate?: string;
  AgencyName?: string;
  Status?: string;
};

/**
 * Query parameter types for payment batch list filtering
 */
export type PaymentBatchListParams = {
  Reference?: string;
  AgencyName?: string;
};
